typography_spectrum: 0.8990757009014487
color:
  brandStrength: 0.36035646847449243
  lightness: 0.2671389526221901
  saturation: 0.5543697474058717
  rhythmicContrast: 0.31167627149261534
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.4453005092218518
author:
  name: Helmut Maier
  email: mail@helmutmaier.berlin
  url: 'http://helmutmaier.berlin'
name: (Blüten) Heil Kraft
navigation:
  - name: Bach Blüten
    id: d24cacfb-3e0c-4a64-b600-bc32c3b2a773
    type: content
title: Die Schwingung macht's
description: Aktiviere dein Potential
