typography_spectrum: 0.42836687224917114
color:
  brandStrength: 0.4629977100994438
  lightness: 0.9616252847481519
  saturation: 0.2107110908254981
  rhythmicContrast: 0.3409546995535493
  brandColors:
    - '#000000'
    - '#2F5231'
    - '#5385DA'
    - '#F5D705'
    - '#F5F5DB'
layout_spectrum: 0.4815029841847718
author:
  name: Helmut Maier
  email: mail@helmutmaier.berlin
  url: 'http://helmutmaier.berlin'
name: (Bl端ten) Heil Kraft
navigation:
  - name: Bach Bl端ten Fotos
    id: 9c87444b-ad8c-4b44-a203-d018bfb21111
    type: content
  - name: Orchideen Essenzen
    id: 2dd69777-36e4-4a16-9fb2-daeac2090a3f
    type: content
  - name: Heilpraxis
    id: f778ad74-0485-4040-a1f4-79c049325afc
    type: content
  - name: Bl端ten & Samen Fotos
    id: 18cc4053-1994-4a3d-8846-66d078958ab8
    type: content
  - name: Bl端ten
    url: 'http://flowerenergies.com/bach-blueten-fotos.html'
    type: external
title: Die Schwingung macht's
description: Aktiviere dein Potential
